USE TatliSozluk

CREATE TABLE Konu(
	konuNo INT IDENTITY(1, 1) PRIMARY KEY,
	konuAd VARCHAR(30) NOT NULL,
)

CREATE TABLE Uye(
	uyeNo INT IDENTITY(1, 1) PRIMARY KEY,
	uyeNick VARCHAR(25) UNIQUE NOT NULL,
	uyeMail VARCHAR(255) UNIQUE NOT NULL,
	uyeDogTar DATE NOT NULL,
	uyeKatTar DATE NOT NULL,
	uyeCins CHAR(1) DEFAULT 'N',
	uyeSifre CHAR(60) NOT NULL,
	
)

CREATE TABLE Baslik(
	baslikNo INT IDENTITY(1, 1) PRIMARY KEY,
	uyeNo INT NOT NULL,
	konuNo INT NOT NULL,
	baslikAd VARCHAR(50) NOT NULL,
	baslikTar SMALLDATETIME NOT NULL,
	CONSTRAINT Baslik_fk_uyeNo FOREIGN KEY (uyeNo) REFERENCES Uye(uyeNo),
	CONSTRAINT Baslik_fk_konuNo FOREIGN KEY (konuNo) REFERENCES Konu(konuNo)
)

CREATE TABLE Yorum(
	yorumNo INT IDENTITY(1, 1) PRIMARY KEY,
	uyeNo INT NOT NULL,
	baslikNo INT NOT NULL,
	yorumTar SMALLDATETIME NOT NULL,
	yorum VARCHAR(8000) NOT NULL, 
	CONSTRAINT Yorum_fk_uyeNo FOREIGN KEY (uyeNo) REFERENCES Uye(uyeNo),
	CONSTRAINT Yorum_fk_baslikNo FOREIGN KEY (baslikNo) REFERENCES Baslik(baslikNo)
)