USE TatliSozluk

INSERT INTO Konu VALUES ('SÝYASET')
INSERT INTO Konu VALUES ('SANAT')
INSERT INTO Konu VALUES ('SPOR')
INSERT INTO Konu VALUES ('EKONOMÝ')
INSERT INTO Konu VALUES ('MÜZÝK')
INSERT INTO Konu VALUES ('BÝLÝM')